## Grafana configuration

replicas: 1

image:
  repository: grafana/grafana
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: grafana

## Use an existing secret for the admin user
adminUser: admin
adminPassword: admin  # Change this in production

service:
  type: ClusterIP
  port: 80
  targetPort: 3000
  annotations: {}

ingress:
  enabled: ${enable_ingress}
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - grafana.${ingress_domain}
  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.${ingress_domain}

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  enabled: true
  size: 10Gi
  storageClassName: ${storage_class_name}

## Configure grafana datasources
## ref: https://grafana.com/docs/grafana/latest/administration/provisioning/#datasources
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.${namespace}.svc.cluster.local
      access: proxy
      isDefault: true
    - name: Loki
      type: loki
      url: http://loki.${namespace}.svc.cluster.local:3100
      access: proxy

## Configure grafana dashboard providers
## ref: https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

## Configure grafana dashboard to import
## ref: https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards
dashboards:
  default:
    kubernetes:
      gnetId: 10000  # Kubernetes cluster monitoring dashboard ID
      revision: 1
      datasource: Prometheus
    node-exporter:
      gnetId: 1860  # Node Exporter dashboard ID
      revision: 23
      datasource: Prometheus
    loki:
      gnetId: 12019  # Loki dashboard ID
      revision: 1
      datasource: Loki

## Grafana's primary configuration
grafana.ini:
  server:
    root_url: "%(protocol)s://%(domain)s/"
  auth:
    disable_login_form: false
  auth.anonymous:
    enabled: true
    org_role: Viewer
  users:
    allow_sign_up: false
    auto_assign_org: true
    auto_assign_org_role: Editor
